### PR TITLE
Fixed issue #57 — Hugo 0.80.0 installation fails

### PR DESCRIPTION
**Pull request by harshvardhaniimi**
Fix was simple. Avoid pinning the Hugo version to 0.80.0 and use the latest version.

### CODE REVIEW

**Comment by harshvardhaniimi** [comment]
Hi @yihui @apreshill  I could help in maintaining this theme.

**Review by yihui — COMMENTED** [review]
I'd rather pin the hugo version but use a version that works for arm64. Could you try to pin it to 0.89.2 (the current latest) and test if the theme still works fine? Thanks!

**Comment by harshvardhaniimi** [comment]
I tested it locally and pinning Hugo version for 0.89.2 works great. I've edited the pull request accordingly.

Could you explain the rationale behind pinning to a specific version? I'm assuming fixing it would mean greater stability but missing out on new features.

**Review by yihui — APPROVED** [review]
> I'm assuming fixing it would mean greater stability but missing out on new features.

That's right. From our experience, stability is much more important than new features. If you do not care about stability, you can of course remove this option in your own project.

Thanks!

**Pull request merged**
